import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import {
  Stack,
  StackDivider,
  Box,
  Button,
  useColorMode,
  Center,
} from "@chakra-ui/react";
import { SunIcon, MoonIcon } from '@chakra-ui/icons'

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <div>
      <Head>
        <title>Random</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack direction="column" justify="space-between" h="100vh" p="2">
        <Stack direction="row-reverse">
          <Button onClick={toggleColorMode}>
            {colorMode == "dark" ? <SunIcon></SunIcon> : <MoonIcon></MoonIcon>}
          </Button>
        </Stack>

        <Center>
          <Box bg="black" color="white" p={5} shadow="md" borderWidth="1px">
            Hello world!
          </Box>
        </Center>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </Stack>
    </div>
  );
}
